export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'

export const backendUrl = 'http://127.0.0.1:8000'




export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'



export const VERIFY_REGISTER_FAIL = 'VERIFY_REGISTER_FAIL'
export const VERIFY_REGISTER_REQUEST = 'VERIFY_REGISTER_REQUEST'
export const VERIFY_REGISTER_SUCCESS = 'VERIFY_REGISTER_SUCCESS'


export const ROOM_DETAIL_FAIL = 'ROOM_DETAIL_FAIL'
export const ROOM_DETAIL_REQUEST = 'ROOM_DETAIL_REQUEST'
export const ROOM_DETAIL_SUCCESS = 'ROOM_DETAIL_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'
export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST'
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'


export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS'
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL'
export const ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST'