export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'


export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'




export const backendUrl = 'http://127.0.0.1:8000'




export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'



export const VERIFY_REGISTER_FAIL = 'VERIFY_REGISTER_FAIL'
export const VERIFY_REGISTER_REQUEST = 'VERIFY_REGISTER_REQUEST'
export const VERIFY_REGISTER_SUCCESS = 'VERIFY_REGISTER_SUCCESS'


export const ROOM_DETAIL_FAIL = 'ROOM_DETAIL_FAIL'
export const ROOM_DETAIL_REQUEST = 'ROOM_DETAIL_REQUEST'
export const ROOM_DETAIL_SUCCESS = 'ROOM_DETAIL_SUCCESS'
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL'
export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST'
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS'


export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS'
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL'
export const ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST'


export const REMOVE_ROOM_REQUEST = 'REMOVE_ROOM_REQUEST'
export const REMOVE_ROOM_SUCCESS = 'REMOVE_ROOM_SUCCESS'
export const REMOVE_ROOM_FAIL = 'REMOVE_ROOM_FAIL'


export const REMOVE_BOOKED_ROOM_REQUEST = "REMOVE_BOOKED_ROOM_REQUEST"
export const REMOVE_BOOKED_ROOM_SUCCESS = "REMOVE_BOOKED_ROOM_SUCCESS"
export const REMOVE_BOOKED_ROOM_FAIL = "REMOVE_BOOKED_ROOM_FAIL"


export const REGISTRATION_DETAIL_FAIL = 'REGISTRATION_DETAIL_FAIL'
export const REGISTRATION_DETAIL_REQUEST = 'REGISTRATION_DETAIL_REQUEST'
export const REGISTRATION_DETAIL_SUCCESS = 'REGISTRATION_DETAIL_SUCCESS'


export const FETCH_MESSAGE_REQUEST = 'FETCH_MESSAGE_REQUEST'
export const FETCH_MESSAGE_FAIL = 'FETCH_MESSAGE_FAIL'
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS'


export const FETCH_PAYMENT_REQUEST = 'FETCH_PAYMENT_REQUEST'
export const FETCH_PAYMENT_FAIL = 'FETCH_PAYMENT_FAIL'
export const FETCH_PAYMENT_SUCCESS = 'FETCH_PAYMENT_SUCCESS'